# Original .travis.yml from https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
language: go
go:
  - 1.10.x

# Anything in before_script that returns a nonzero exit code will
# flunk the build and immediately stop. It's sorta like having
# set -e enabled in bash. 
before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - GO_FOLDERS = $(go list ./... | grep LAtanassov)
  - go get golang.org/x/vgo
  - go get github.com/golang/lint/golint                        # Linter
  - go get honnef.co/go/tools/cmd/megacheck                     # Badass static analyzer/linter
  - go get github.com/fzipp/gocyclo

# script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
script:
  - test -z $(vgo fmt ./...)                 # Fail if a .go file hasn't been formatted with gofmt
  - vgo test -v -race ./...                  # Run all the tests with the race detector enabled
  - vgo vet $GO_FOLDERS                 # go vet is the official Go static analyzer
  - vgo mod -vendor
  - megacheck ./...                          # "go vet on steroids" + linter
  - gocyclo -over 19 $GO_FILES               # forbid code with huge functions
  - golint -set_exit_status $(go list ./...) # one last linter