apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: orders-deployment
spec:
  selector:
    matchLabels:
      app: orders
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: orders
        tier: backend
    spec:
      containers:
        - image: latanassov/orders
          name: orders-pod
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_DATABASE
              value: godax
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: orders
    tier: backend
